# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'traderTool.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import date


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(886, 671)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(80, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        MainWindow.setPalette(palette)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.setRiskButton = QtWidgets.QPushButton(self.centralwidget)
        self.setRiskButton.setGeometry(QtCore.QRect(30, 230, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.setRiskButton.setFont(font)
        self.setRiskButton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
                                         "background-color: rgb(255, 34, 34);\n"
                                         "font: 75 14pt \"Adobe Gothic Std B\";")
        self.setRiskButton.setObjectName("setRiskButton")
        self.setStopButton = QtWidgets.QPushButton(self.centralwidget)
        self.setStopButton.setGeometry(QtCore.QRect(230, 230, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.setStopButton.setFont(font)
        self.setStopButton.setStyleSheet("background-color: rgb(252, 215, 26);\n"
                                         "border-color: rgb(0, 0, 0);\n"
                                         "font: 75 14pt \"Adobe Gothic Std B\";")
        self.setStopButton.setObjectName("setStopButton")
        self.setTargetButton = QtWidgets.QPushButton(self.centralwidget)
        self.setTargetButton.setGeometry(QtCore.QRect(330, 230, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.setTargetButton.setFont(font)
        self.setTargetButton.setStyleSheet("background-color: rgb(252, 215, 26);\n"
                                           "border-color: rgb(0, 0, 0);\n"
                                           "font: 75 14pt \"Adobe Gothic Std B\";")
        self.setTargetButton.setObjectName("setTargetButton")
        self.openTradeButton = QtWidgets.QPushButton(self.centralwidget)
        self.openTradeButton.setGeometry(QtCore.QRect(130, 330, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.openTradeButton.setFont(font)
        self.openTradeButton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
                                           "background-color: rgb(255, 34, 34);\n"
                                           "font: 75 14pt \"Adobe Gothic Std B\";")
        self.openTradeButton.setObjectName("openTradeButton")
        self.openOrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.openOrderButton.setGeometry(QtCore.QRect(30, 330, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.openOrderButton.setFont(font)
        self.openOrderButton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
                                           "background-color: rgb(255, 34, 34);\n"
                                           "font: 75 14pt \"Adobe Gothic Std B\";")
        self.openOrderButton.setObjectName("openOrderButton")
        self.doubleOrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.doubleOrderButton.setGeometry(QtCore.QRect(230, 330, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.doubleOrderButton.setFont(font)
        self.doubleOrderButton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
                                             "background-color: rgb(255, 34, 34);\n"
                                             "font: 75 14pt \"Adobe Gothic Std B\";")
        self.doubleOrderButton.setObjectName("doubleOrderButton")
        self.closeCustomButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeCustomButton.setGeometry(QtCore.QRect(230, 430, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.closeCustomButton.setFont(font)
        self.closeCustomButton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
                                             "background-color: rgb(255, 34, 34);\n"
                                             "font: 75 14pt \"Adobe Gothic Std B\";")
        self.closeCustomButton.setObjectName("closeCustomButton")
        self.closeAllButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeAllButton.setGeometry(QtCore.QRect(30, 430, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.closeAllButton.setFont(font)
        self.closeAllButton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
                                          "background-color: rgb(255, 34, 34);\n"
                                          "font: 75 14pt \"Adobe Gothic Std B\";")
        self.closeAllButton.setObjectName("closeAllButton")
        self.closeHalfButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeHalfButton.setGeometry(QtCore.QRect(130, 430, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.closeHalfButton.setFont(font)
        self.closeHalfButton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
                                           "background-color: rgb(255, 34, 34);\n"
                                           "font: 75 14pt \"Adobe Gothic Std B\";")
        self.closeHalfButton.setObjectName("closeHalfButton")
        self.autoBeButton = QtWidgets.QPushButton(self.centralwidget)
        self.autoBeButton.setGeometry(QtCore.QRect(230, 530, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.autoBeButton.setFont(font)
        self.autoBeButton.setStyleSheet("background-color: rgb(0, 170, 127);\n"
                                        "border-color: rgb(0, 0, 0);\n"
                                        "font: 75 14pt \"Adobe Gothic Std B\";")
        self.autoBeButton.setObjectName("autoBeButton")
        self.runnerButton = QtWidgets.QPushButton(self.centralwidget)
        self.runnerButton.setGeometry(QtCore.QRect(30, 530, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.runnerButton.setFont(font)
        self.runnerButton.setStyleSheet("background-color: rgb(0, 170, 127);\n"
                                        "border-color: rgb(0, 0, 0);\n"
                                        "font: 75 14pt \"Adobe Gothic Std B\";")
        self.runnerButton.setObjectName("runnerButton")
        self.partialTPButton = QtWidgets.QPushButton(self.centralwidget)
        self.partialTPButton.setGeometry(QtCore.QRect(130, 530, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.partialTPButton.setFont(font)
        self.partialTPButton.setStyleSheet("background-color: rgb(0, 170, 127);\n"
                                           "border-color: rgb(0, 0, 0);\n"
                                           "font: 75 14pt \"Adobe Gothic Std B\";")
        self.partialTPButton.setObjectName("partialTPButton")
        self.targetAtRatioButton = QtWidgets.QPushButton(self.centralwidget)
        self.targetAtRatioButton.setGeometry(QtCore.QRect(430, 230, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.targetAtRatioButton.setFont(font)
        self.targetAtRatioButton.setStyleSheet("background-color: rgb(252, 215, 26);\n"
                                               "border-color: rgb(0, 0, 0);\n"
                                               "font: 75 14pt \"Adobe Gothic Std B\";")
        self.targetAtRatioButton.setObjectName("targetAtRatioButton")
        self.halfRiskButton = QtWidgets.QPushButton(self.centralwidget)
        self.halfRiskButton.setGeometry(QtCore.QRect(330, 530, 91, 85))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(80, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.halfRiskButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.halfRiskButton.setFont(font)
        self.halfRiskButton.setStyleSheet("background-color: rgb(0, 170, 127);\n"
                                          "font: 75 14pt \"Adobe Gothic Std B\";\n"
                                          "border-color: rgb(0, 0, 0);\n"
                                          "")
        self.halfRiskButton.setObjectName("halfRiskButton")
        self.getPositionsButton = QtWidgets.QPushButton(self.centralwidget)
        self.getPositionsButton.setGeometry(QtCore.QRect(330, 330, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.getPositionsButton.setFont(font)
        self.getPositionsButton.setStyleSheet("background-color: rgb(252, 215, 26);\n"
                                              "border-color: rgb(0, 0, 0);\n"
                                              "font: 75 14pt \"Adobe Gothic Std B\";")
        self.getPositionsButton.setObjectName("getPositionsButton")
        self.getOrdersButton = QtWidgets.QPushButton(self.centralwidget)
        self.getOrdersButton.setGeometry(QtCore.QRect(330, 430, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.getOrdersButton.setFont(font)
        self.getOrdersButton.setStyleSheet("background-color: rgb(252, 215, 26);\n"
                                           "border-color: rgb(0, 0, 0);\n"
                                           "font: 75 14pt \"Adobe Gothic Std B\";")
        self.getOrdersButton.setObjectName("getOrdersButton")
        self.contractComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.contractComboBox.setGeometry(QtCore.QRect(670, 110, 190, 40))
        self.contractComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.contractComboBox.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.contractComboBox.setObjectName("contractComboBox")
        self.contractComboBox.addItem("")
        self.contractComboBox.addItem("")
        self.contractComboBox.addItem("")
        self.priceSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.priceSpinBox.setGeometry(QtCore.QRect(30, 160, 191, 61))
        self.priceSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.priceSpinBox.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.priceSpinBox.setDecimals(3)
        self.priceSpinBox.setMaximum(10000.0)
        self.priceSpinBox.setSingleStep(0.001)
        self.priceSpinBox.setObjectName("priceSpinBox")
        self.riskSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.riskSpinBox.setGeometry(QtCore.QRect(230, 160, 91, 61))
        self.riskSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.riskSpinBox.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.riskSpinBox.setSingleStep(0.25)
        self.riskSpinBox.setObjectName("riskSpinBox")
        self.mainPriceLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainPriceLabel.setGeometry(QtCore.QRect(30, 120, 111, 31))
        self.mainPriceLabel.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.mainPriceLabel.setObjectName("mainPriceLabel")
        self.mainRiskLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainRiskLabel.setGeometry(QtCore.QRect(230, 120, 111, 31))
        self.mainRiskLabel.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.mainRiskLabel.setObjectName("mainRiskLabel")
        self.checkPosButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkPosButton.setGeometry(QtCore.QRect(430, 330, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.checkPosButton.setFont(font)
        self.checkPosButton.setStyleSheet("background-color: rgb(252, 215, 26);\n"
                                          "border-color: rgb(0, 0, 0);\n"
                                          "font: 75 14pt \"Adobe Gothic Std B\";")
        self.checkPosButton.setObjectName("checkPosButton")
        self.setPriceButton = QtWidgets.QPushButton(self.centralwidget)
        self.setPriceButton.setGeometry(QtCore.QRect(130, 230, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.setPriceButton.setFont(font)
        self.setPriceButton.setStyleSheet("background-color: rgb(252, 215, 26);\n"
                                          "border-color: rgb(0, 0, 0);\n"
                                          "font: 75 14pt \"Adobe Gothic Std B\";")
        self.setPriceButton.setObjectName("setPriceButton")
        self.entryPriceBox = QtWidgets.QLineEdit(self.centralwidget)
        self.entryPriceBox.setGeometry(QtCore.QRect(670, 260, 181, 41))
        self.entryPriceBox.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.entryPriceBox.setText("")
        self.entryPriceBox.setReadOnly(True)
        self.entryPriceBox.setObjectName("entryPriceBox")
        self.entryPriceLabel = QtWidgets.QLabel(self.centralwidget)
        self.entryPriceLabel.setGeometry(QtCore.QRect(670, 230, 181, 21))
        self.entryPriceLabel.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.entryPriceLabel.setObjectName("entryPriceLabel")
        self.stopLossBox = QtWidgets.QLineEdit(self.centralwidget)
        self.stopLossBox.setGeometry(QtCore.QRect(670, 340, 181, 41))
        self.stopLossBox.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.stopLossBox.setText("")
        self.stopLossBox.setReadOnly(True)
        self.stopLossBox.setObjectName("stopLossBox")
        self.stopLossLabel = QtWidgets.QLabel(self.centralwidget)
        self.stopLossLabel.setGeometry(QtCore.QRect(670, 310, 181, 21))
        self.stopLossLabel.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.stopLossLabel.setObjectName("stopLossLabel")
        self.takeProfitBox = QtWidgets.QLineEdit(self.centralwidget)
        self.takeProfitBox.setGeometry(QtCore.QRect(670, 420, 181, 41))
        self.takeProfitBox.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.takeProfitBox.setText("")
        self.takeProfitBox.setReadOnly(True)
        self.takeProfitBox.setObjectName("takeProfitBox")
        self.takeProfitLabel = QtWidgets.QLabel(self.centralwidget)
        self.takeProfitLabel.setGeometry(QtCore.QRect(670, 390, 181, 21))
        self.takeProfitLabel.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.takeProfitLabel.setObjectName("takeProfitLabel")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setDate(date.today())
        self.dateTimeEdit.setTime(QtCore.QTime(23, 50, 0))
        self.dateTimeEdit.setEnabled(False)
        self.dateTimeEdit.setGeometry(QtCore.QRect(670, 160, 191, 41))
        self.dateTimeEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateTimeEdit.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.setDevButton = QtWidgets.QPushButton(self.centralwidget)
        self.setDevButton.setGeometry(QtCore.QRect(430, 430, 91, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.setDevButton.setFont(font)
        self.setDevButton.setStyleSheet("background-color: rgb(252, 215, 26);\n"
                                            "border-color: rgb(0, 0, 0);\n"
                                            "font: 75 14pt \"Adobe Gothic Std B\";")
        self.setDevButton.setObjectName("checkPosButton_2")
        self.orderTypeComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.orderTypeComboBox.setGeometry(QtCore.QRect(330, 160, 191, 61))
        self.orderTypeComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.orderTypeComboBox.setAutoFillBackground(False)
        self.orderTypeComboBox.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.orderTypeComboBox.setObjectName("orderTypeComboBox")
        self.orderTypeComboBox.addItem("")
        self.orderTypeComboBox.addItem("")
        self.orderTypeComboBox.addItem("")
        self.orderTypeComboBox.addItem("")
        self.orderTypeComboBox.addItem("")
        self.orderTypeComboBox.addItem("")
        self.riskBox = QtWidgets.QLineEdit(self.centralwidget)
        self.riskBox.setGeometry(QtCore.QRect(670, 500, 41, 41))
        self.riskBox.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.riskBox.setText("")
        self.riskBox.setReadOnly(True)
        self.riskBox.setObjectName("riskBox")
        self.riskLabel = QtWidgets.QLabel(self.centralwidget)
        self.riskLabel.setGeometry(QtCore.QRect(670, 470, 181, 21))
        self.riskLabel.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.riskLabel.setObjectName("riskLabel")
        self.devBox = QtWidgets.QLineEdit(self.centralwidget)
        self.devBox.setGeometry(QtCore.QRect(810, 500, 41, 41))
        self.devBox.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.devBox.setText("")
        self.devBox.setReadOnly(True)
        self.devBox.setObjectName("devBox")
        self.devLabel = QtWidgets.QLabel(self.centralwidget)
        self.devLabel.setGeometry(QtCore.QRect(810, 470, 181, 21))
        self.devLabel.setStyleSheet("font: 75 14pt \"Adobe Gothic Std B\";")
        self.devLabel.setObjectName("devLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 886, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spooks FX"))
        self.setRiskButton.setText(_translate("MainWindow", "Set \nRisk"))
        self.setStopButton.setText(_translate("MainWindow", "Set \nSL"))
        self.setTargetButton.setText(_translate("MainWindow", "Set \nTP"))
        self.openTradeButton.setText(_translate("MainWindow", "Open \nTrade"))
        self.openOrderButton.setText(_translate("MainWindow", "Open \nOrder"))
        self.doubleOrderButton.setText(_translate("MainWindow", "Double \nOrder"))
        self.closeCustomButton.setText(_translate("MainWindow", "Close \nCustom"))
        self.closeAllButton.setText(_translate("MainWindow", "Close \nAll"))
        self.closeHalfButton.setText(_translate("MainWindow", "Close \nHalf"))
        self.autoBeButton.setText(_translate("MainWindow", "Auto \nBE"))
        self.runnerButton.setText(_translate("MainWindow", "Runner"))
        self.partialTPButton.setText(_translate("MainWindow", "Partial \nTP"))
        self.targetAtRatioButton.setText(_translate("MainWindow", "TP \n@ 1:x"))
        self.halfRiskButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.halfRiskButton.setText(_translate("MainWindow", "Half \nRisk"))
        self.getPositionsButton.setText(_translate("MainWindow", "Get \nPositions"))
        self.getOrdersButton.setText(_translate("MainWindow", "Get \nOrders"))
        self.contractComboBox.setItemText(0, _translate("MainWindow", "GTC"))
        self.contractComboBox.setItemText(1, _translate("MainWindow", "Today"))
        self.contractComboBox.setItemText(2, _translate("MainWindow", "Specified"))
        self.mainPriceLabel.setText(_translate("MainWindow", "Price"))
        self.mainRiskLabel.setText(_translate("MainWindow", "Risk / Dev"))
        self.checkPosButton.setText(_translate("MainWindow", "Check \nPosition"))
        self.setPriceButton.setText(_translate("MainWindow", "Set \nPrice"))
        self.entryPriceLabel.setText(_translate("MainWindow", "Entry \nPrice"))
        self.stopLossLabel.setText(_translate("MainWindow", "Stop \nLoss"))
        self.takeProfitLabel.setText(_translate("MainWindow", "Take Profit"))
        self.setDevButton.setText(_translate("MainWindow", "Set \nDev"))
        self.orderTypeComboBox.setItemText(0, _translate("MainWindow", "Buy"))
        self.orderTypeComboBox.setItemText(1, _translate("MainWindow", "Sell"))
        self.orderTypeComboBox.setItemText(2, _translate("MainWindow", "Buy Limit"))
        self.orderTypeComboBox.setItemText(3, _translate("MainWindow", "Sell Limit"))
        self.orderTypeComboBox.setItemText(4, _translate("MainWindow", "Buy Stop"))
        self.orderTypeComboBox.setItemText(5, _translate("MainWindow", "Sell Stop"))
        self.riskLabel.setText(_translate("MainWindow", "Risk"))
        self.devLabel.setText(_translate("MainWindow", "Dev"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
